// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    ButtonRepo: typeof import('./components/ButtonRepo.vue')['default']
    Content: typeof import('./components/Content.vue')['default']
    CopyRight: typeof import('./components/CopyRight.vue')['default']
    Features: typeof import('./components/Features.vue')['default']
    GithubRibbon: typeof import('./components/GithubRibbon.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    MyFooter: typeof import('./components/MyFooter.vue')['default']
    MyHeader: typeof import('./components/MyHeader.vue')['default']
    Pricing: typeof import('./components/Pricing.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
